name: trieugene
up:
  - homebrew:
    - golangci/tap/golangci-lint
  - go:
      version: 1.13
      modules: true
  - railgun
commands:
  build: make build
  rougecombien: go run services/rougecombien/cmd/rougecombien/main.go dev
  trieugene: go run cmd/trieugene/main.go dev
