name: trieugene
up:
  - homebrew:
    - golangci/tap/golangci-lint
  - go:
      version: 1.13
      modules: true
  - railgun
commands:
  trieugene: go build -o bin/trieugene cmd/trieugene/main.go
  rougecombien: go build -o bin/rougecombien services/rougecombien/cmd/rougecombien/main.go