name: trieugene
up:
  - homebrew:
    - golangci-lint
  - go:
      version: "1.17.6"
      modules: true
commands:
  build: make build
  rougecombien: go run services/rougecombien/cmd/rougecombien/main.go dev
  trieugene: go run cmd/trieugene/main.go dev
