name: trieugene

vm:
  image: /opt/dev/misc/railgun-images/default
  ip_address: 192.168.64.83
  memory:     2G
  cores:      2

volumes:
  root:  '2G'

services:
  - nginx

custom_services:
    - pubsub:
        healthcheck_port: 8432
        image: 'singularities/pubsub-emulator'
        env:
          PUBSUB_LISTEN_ADDRESS: 0.0.0.0:8432
          PUBSUB_PROJECT_ID: trieugene1
    - gcs:
        healthcheck_port: 4443
        image: fsouza/fake-gcs-server

hostnames:
  - trieugene.myshopify.io: { proxy_to_host_port: 9602 }
