name: trieugene

vm:
  image: /opt/dev/misc/railgun-images/default
  ip_address: 192.168.64.83
  memory:     2G
  cores:      2

volumes:
  root:  '2G'

services:
  - nginx

custom_services:
    - faktory:
        healthcheck_port: 7419
        image: 'contribsys/faktory'
    - fakes3:
        healthcheck_port: 8000
        image: fingershock/fakes3

hostnames:
  - trieugene.myshopify.io: { proxy_to_host_port: 9602 }
